apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "init-job.fullname" . }}
  labels:
    app: {{ include "init-job.name" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "init-job.name" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.name }}
