kafka:
  brokers:
    - kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  pagesTopic: crawler-pages
  hostsTopic: crawler-hosts

redis:
  addr: redis.redis.svc.cluster.local:6379

crawler:
  maxWorkers: 5
  maxPagesPerHost: 500
